package Vista;

/**
 *
 * @author juan.ucan
 */
public class FrmInicio extends javax.swing.JFrame {

    /**
     * Creates new form FrmInicio
     */
    public FrmInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        lbTitulo = new javax.swing.JLabel();
        lbImagen = new javax.swing.JLabel();
        menuBarInicio = new javax.swing.JMenuBar();
        menuEmpleados = new javax.swing.JMenu();
        menuItemAsalariado = new javax.swing.JMenuItem();
        menuItemPorComision = new javax.swing.JMenuItem();
        menuItemBaseMasComision = new javax.swing.JMenuItem();
        menuItemPorHoras = new javax.swing.JMenuItem();
        menuItemSalir = new javax.swing.JMenuItem();
        menuPagos = new javax.swing.JMenu();
        menuItemFacturaNueva = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        menuItemNomina = new javax.swing.JMenuItem();
        menuItemFacturas = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        lbTitulo.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lbTitulo.setForeground(new java.awt.Color(0, 51, 255));
        lbTitulo.setText("Sistema de Recursos Humanos");

        lbImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/rh.jpg"))); // NOI18N

        menuEmpleados.setText("Empleados");

        menuItemAsalariado.setText("Asalariado");
        menuItemAsalariado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAsalariadoActionPerformed(evt);
            }
        });
        menuEmpleados.add(menuItemAsalariado);

        menuItemPorComision.setText("Por Comision");
        menuItemPorComision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPorComisionActionPerformed(evt);
            }
        });
        menuEmpleados.add(menuItemPorComision);

        menuItemBaseMasComision.setText("Base Más Comisión");
        menuItemBaseMasComision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemBaseMasComisionActionPerformed(evt);
            }
        });
        menuEmpleados.add(menuItemBaseMasComision);

        menuItemPorHoras.setText("Por Horas");
        menuItemPorHoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPorHorasActionPerformed(evt);
            }
        });
        menuEmpleados.add(menuItemPorHoras);

        menuItemSalir.setText("Salir");
        menuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSalirActionPerformed(evt);
            }
        });
        menuEmpleados.add(menuItemSalir);

        menuBarInicio.add(menuEmpleados);

        menuPagos.setText("Pagos");

        menuItemFacturaNueva.setText("Nueva factura");
        menuItemFacturaNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemFacturaNuevaActionPerformed(evt);
            }
        });
        menuPagos.add(menuItemFacturaNueva);

        menuBarInicio.add(menuPagos);

        menuReportes.setText("Reportes");

        menuItemNomina.setText("Nómina");
        menuItemNomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNominaActionPerformed(evt);
            }
        });
        menuReportes.add(menuItemNomina);

        menuItemFacturas.setText("Facturas");
        menuItemFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemFacturasActionPerformed(evt);
            }
        });
        menuReportes.add(menuItemFacturas);

        menuBarInicio.add(menuReportes);

        setJMenuBar(menuBarInicio);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbImagen)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTitulo)
                .addGap(84, 84, 84))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lbTitulo)
                .addGap(18, 18, 18)
                .addComponent(lbImagen)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_menuItemSalirActionPerformed

    private void menuItemAsalariadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAsalariadoActionPerformed
        // TODO add your handling code here:
        new FrmEmpleadoAsalariado().setVisible(true);
    }//GEN-LAST:event_menuItemAsalariadoActionPerformed

    private void menuItemNominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNominaActionPerformed
        // TODO add your handling code here:
         new FrmNomina().setVisible(true);
    }//GEN-LAST:event_menuItemNominaActionPerformed

    private void menuItemFacturaNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemFacturaNuevaActionPerformed
        // TODO add your handling code here:
        new FrmFactura().setVisible(true);
    }//GEN-LAST:event_menuItemFacturaNuevaActionPerformed

    private void menuItemFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemFacturasActionPerformed
        // TODO add your handling code here:
        new FrmFacturas().setVisible(true);
    }//GEN-LAST:event_menuItemFacturasActionPerformed

    private void menuItemPorComisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPorComisionActionPerformed
        // TODO add your handling code here:
        new FrmEmpleadoComision().setVisible(true);
    }//GEN-LAST:event_menuItemPorComisionActionPerformed

    private void menuItemBaseMasComisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemBaseMasComisionActionPerformed
        // TODO add your handling code here:
        new FrmEmpleadoBaseComision().setVisible(true);
    }//GEN-LAST:event_menuItemBaseMasComisionActionPerformed

    private void menuItemPorHorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPorHorasActionPerformed
        // TODO add your handling code here:
        new FrmEmpleadoPorHoras().setVisible(true);
    }//GEN-LAST:event_menuItemPorHorasActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lbImagen;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JMenuBar menuBarInicio;
    private javax.swing.JMenu menuEmpleados;
    private javax.swing.JMenuItem menuItemAsalariado;
    private javax.swing.JMenuItem menuItemBaseMasComision;
    private javax.swing.JMenuItem menuItemFacturaNueva;
    private javax.swing.JMenuItem menuItemFacturas;
    private javax.swing.JMenuItem menuItemNomina;
    private javax.swing.JMenuItem menuItemPorComision;
    private javax.swing.JMenuItem menuItemPorHoras;
    private javax.swing.JMenuItem menuItemSalir;
    private javax.swing.JMenu menuPagos;
    private javax.swing.JMenu menuReportes;
    // End of variables declaration//GEN-END:variables
}
